name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14.x
      - run: npm i
      - run: PUBLIC_URL="/ui" npm run build
      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=ref_name::$(echo ${{ github.ref }} | sed 's/.*\///')"
      - name: package
        run: tar -C build -zcvf "${{ steps.vars.outputs.ref_name }}.tgz" .
      - name: release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          name: ${{ steps.vars.outputs.ref_name }}
          tag_name: ${{ steps.vars.outputs.ref_name }}
          files: ${{ steps.vars.outputs.ref_name }}.tgz
        env:
          GITHUB_TOKEN: ${{ github.token }}
